# Original Work: https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml

name: '[Reusable] Terraform Destroy'

on:
  workflow_call:
    inputs:
      ACT_MODE:
        description: |
          For running Github Action Workflows locally with Nektos act
        required: true
        type: boolean
    
    secrets:
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT_EMAIL:
        description: |
          Google Cloud Service Account Impersonator for authentication
        required: true
      GOOGLE_PROJECT:
        description: |
          Google Cloud Project ID
        required: true
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER:
        description: |
          Google Cloud Workload Identity Federation Provider Member ID
        required: false
      GOOGLE_OAUTH_ACCESS_TOKEN:
        description: |
          Google Cloud OAauth2 Access Token
        required: false
      TF_API_TOKEN:
        description: |
          Terraform.io Access Token
        required: true

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  GOOGLE_PROJECT: "${{ secrets.GOOGLE_PROJECT }}"
  GOOGLE_OAUTH_ACCESS_TOKEN: "${{ secrets.GOOGLE_OAUTH_ACCESS_TOKEN }}"
  TF_VAR_IMPERSONATE_SERVICE_ACCOUNT_EMAIL: "${{ secrets.GOOGLE_IMPERSONATE_SERVICE_ACCOUNT_EMAIL }}"

jobs:
  reusable-integration-destroy:
    name: 'Terraform Destroy'
    environment: production
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./test"

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure GCP Credentials - Github Runner
      uses: 'google-github-actions/auth@v2'
      if: ${{ !inputs.ACT_MODE }}
      with:
        service_account: "${{ secrets.GOOGLE_IMPERSONATE_SERVICE_ACCOUNT_EMAIL }}"
        workload_identity_provider: "${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
    
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
    
    # Terraform Destroy
    - name: Terraform Destroy
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: 'terraform -chdir=test destroy --auto-approve'